package core;

public enum GameStates {
    MOVING,
    CHANCE_NOTIFICATION, VICTORY_NOTIFICATION, WALL_NOTIFICATION, EXAMPLE_NOTIFICATION,
    GAMEBOARD_IDLE, GAME_OVER, END_TURN, NEW_TURN, MASTERPIECE_RULES

}
