package core;

public enum GameStates {
    MOVING,
    CHANCE_NOTIFICATION, VICTORY_NOTIFICATION, WALL_NOTIFICATION, EXAMPLE_NOTIFICATION,
    GAMEBOARD_IDLE, GAME_OVER, END_TURN, NEW_TURN, MASTERPIECE_RULES,
    MINIGAME_LAUNCH,
    MINIGAME_INSTRUCTIONS,
    MINIGAME_PLAYER_READY,
    MINIGAME_PLAY,
    MINIGAME_PLAY_OVER,
    MINIGAME_RESULTS

}
